name: Lint and Auto-Fix Code

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint_and_fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install black isort flake8

      - name: Run black
        run: black .

      - name: Run isort
        run: isort .

      - name: Run flake8 (lint only)
        run: flake8 .

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

